# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20160829_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SmallIntegerField(blank=True, choices=[(1, 'Undetermined'), (2, 'Accepted'), (3, 'Declined')], default=1, verbose_name='Flag')),
                ('start_time', models.TimeField(default=datetime.datetime(2016, 11, 17, 14, 26, 47, 32382))),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Application')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
