# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continiousauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authenticationsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 14, 49, 4, 867459)),
        ),
    ]
