# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continiousauth', '0002_auto_20161117_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationsession',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='authenticationsession',
            name='external_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authenticationsession',
            name='session_photo_bytes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authenticationsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 16, 12, 22, 22000)),
        ),
    ]
