# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='authentication_url_failure',
            field=models.URLField(default='www.example.com/failure'),
        ),
        migrations.AddField(
            model_name='application',
            name='authentication_url_success',
            field=models.URLField(default='www.example.com/success'),
        ),
    ]
